# WARNING: This build file assume that the sub-modules have been retrieved.

./ : lib{colony} : hxx{**}

lib{colony} :
{
    cxx.export.poptions = "-I$out_base" "-I$src_base"
}

hxx{*}:
{
    install = include/
    install.subdirs = false
}

cxx.poptions =+ "-I$out_base" "-I$src_base"
